title: Target practice
hero_image: images/banner.png
description: Use Python to draw a target and score points by hitting it with arrows.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Create a background
  - title: Draw your target
  - title: Fire the arrow
  - title: Score points
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
