---
title: लक्ष्य अभ्यास
hero_image: images/banner.png
description: एक लक्ष्य बनाने के लिए पाइथन का उपयोग करें और इसे तीर से मारते हुए अंक स्कोर करें
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: एक पृष्ठभूमि बनाएँ
  - 
    title: अपना लक्ष्य बनाएँ
    completion:
      - engaged
  - 
    title: अपनी तीर चलाएँ
  - 
    title: अंक स्कोर करें
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: प्रोजेक्ट को अपग्रेड करें
  - 
    title: आगे क्या?
