---
title: Tiro al blanco
hero_image: images/banner.png
description: Usa Python para dibujar un blanco y ganar puntos golpeándolo con flechas
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Lo que harás
  - 
    title: Crea un fondo
  - 
    title: Dibuja tu blanco
    completion:
      - engaged
  - 
    title: Dispara tu flecha
  - 
    title: Gana puntos
    completion:
      - internal
  - 
    title: Examen rapido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
