---
title: Tiro al blanco
hero_image: images/banner.png
description: Usa Python para dibujar un blanco y ganar puntos golpeándolo con flechas
meta_title: Proyectos de codificación Python para niños y adolescentes | Práctica de tiro al blanco
meta_description: Aprende Python con los proyectos de codificación de la Fundación Raspberry Pi para niños y adolescentes. Usa Python para dibujar un objetivo y ganar puntos tirando flechas.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Lo que harás
  - 
    title: Crea un fondo
  - 
    title: Dibuja tu blanco
    completion:
      - comprometido
  - 
    title: Dispara tu flecha
  - 
    title: Gana puntos
    completion:
      - interno
  - 
    title: Examen rapido
    knowledge_quiz:
      path: prueba1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - externo
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
